/** Canonical app paths — use for nav, footer, and redirects. */
export const routes = {
  home: "/",
  shop: "/shop",
  productsIndex: "/products",
  productsDefault: "/products/passenger-cars",
  product: (slug) => `/products/${encodeURIComponent(slug)}`,
  category: (categorySlug) => `/products/${encodeURIComponent(categorySlug)}`,
  about: "/about",
  contact: "/contact",
  cart: "/cart",
  cartAddress: "/cart/address",
  cartShipping: "/cart/shipping",
  cartPayment: "/cart/payment",
  cartPaymentReturn: "/cart/payment/return",
  checkout: "/checkout",
  account: "/account",
  accountOrders: "/account/orders",
  accountAddresses: "/account/addresses",
  signIn: "/sign-in",
  signUp: "/sign-in?intent=register",
  forgotPassword: "/forgot-password",
  verifyOtp: "/verify-otp",
  resetPassword: "/reset-password",
  businessRegister: "/business/register",
  disclaimer: "/disclaimer",
  privacy: "/privacy",
  cookies: "/cookies",
  terms: "/terms",
  components: "/components",
};
