export const EMPTY_ADDRESS_FORM = {
  contact: { email: "", marketingOptIn: true },
  delivery: {
    label: "",
    addressPreview: "",
    recipientId: "primary",
    selectedAddressId: "",
    addressKind: "home",
  },
  recipients: [
    { id: "primary", name: "", phone: "", selected: true },
    { id: "other", name: "Someone else will be at the door", phone: "", selected: false },
  ],
  accountType: "personal",
  billingSameAsShipping: true,
  billing: {
    countryCode: "SA",
    buildingNo: "",
    street: "",
    secondary: "",
    district: "",
    postalCode: "",
    city: "",
    stateProvince: "",
    phoneCountry: "+966",
    phone: "",
  },
  purchaseOrderNumber: "",
  location: {
    lat: null,
    lng: null,
    placeId: "",
    formattedAddress: "",
  },
  countryCode: "SA",
  buildingNo: "",
  street: "",
  secondary: "",
  district: "",
  postalCode: "",
  city: "",
  stateProvince: "",
  landmark: "",
  nationalAddress: "",
  companyFloor: "",
  phoneCountry: "+966",
  phone: "",
  email: "",
  portOfDestination: "",
  freightType: "",
  warehouseSlug: "",
  business: {
    country: "Saudi Arabia",
    organizationName: "",
    organizationNameAr: "",
    crNumber: "",
    vatNumber: "",
    invitationCode: "",
    buildingNo: "",
    street: "",
    secondary: "",
    district: "",
    postalCode: "",
    city: "",
    email: "",
    phone: "",
  },
};
